### ISSUE TITLE
Updating structure of the project

### ISSUE THREAD

**Issue by Dzordzu** [Rekseto/PolishWebDevForBeginners#15]
The main idea is to modularize code. The question is how we should do it. I suggest following options:
1. Core sources, info and links in the README.md, rest in the github wiki (could be ambiguous for beginners)
2. Core info in the README.md, rest in the github.io pages (seems the best option for me)
3. Everything in separate .md files

**Comment by xxczaki** [comment]
I prefer the second option :smile:

**Comment by Rekseto** [comment]
Im able to start updating structure today :3 of course for the voice of the people we can choose second option

**Comment by Dzordzu** [comment]
Maybe, in order to prevent unnecessary ambiguity, we should take this transformation in several steps. By this I want to say that at the beginning we can create the set of .md files, and then (if the amount of the information is overwhelming) we can move to the Jekyll or something like that
