### ISSUE TITLE
Problems with project git history

### ISSUE THREAD

**Issue by Dzordzu** [Rekseto/PolishWebDevForBeginners#16]
Because of the miss-click of the one of the contributors (@Rekseto we see ya) the unwanted force merge has been applied to the project. Anyone who feels (and sees) that theirs changes have been removed should make a new pull request. We are sorry for any inconvenience.

**Comment by Dzordzu** [comment]
@xxczaki You should look there. AFAIK it touches only your commits

**Comment by xxczaki** [comment]
@Dzordzu Thanks, I will make a PR soon ;)
