### ISSUE TITLE
Add typeorm

### ISSUE THREAD

**Issue by ScuroGuardiano** [Rekseto/PolishWebDevForBeginners#34]
Would you mind to add typeorm framework to databases? It's great typescript/javascript ORM with very good documentation, imo the best ORM for projects written in typescript. Link -> https://typeorm.io/#/

**Comment by Dzordzu** [comment]
Just make a pull request with links that you consider important. You should also prepare a short description.

I suggest inserting it in [JS section](https://github.com/Rekseto/PolishWebDevForBeginners/blob/master/js.md)

**Comment by ScuroGuardiano** [comment]
Okey, will do
